name: App_GoHighlevel
description: App as test assignment.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0
  go_router: ^9.1.0

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  

  flutter_lints: ^2.0.0
  flutter_driver:
    sdk: flutter
  test: ^1.24.1

flutter:
  uses-material-design: true